server:
  session_secret: "change-me-in-production"

datasources:
  - name: prod
    type: prometheus
    url: "http://dummyprom:9090"
    timeout: 30s
    default: true
  - name: staging
    type: prometheus
    url: "http://dummyprom:9090/staging"
    timeout: 30s

# Default user: admin / admin
# Generate a new hash with: dashyard mkpasswd <password>
users:
  - id: "admin"
    password_hash: "$6$D/BkIQYiHD.cKL4A$pbAApV8cWXOv3hTyITrHNmlWe3FyfIJyM2CVFuJxbmXwDZPIVbcXKJbM2dxmJqG/ZJZBtrt8e9bVxt0d7rQKK."
