services:
  dashyard:
    build:
      context: ../..
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./config-docker.yaml:/etc/dashyard/config.yaml:ro
      - ./dashboards:/etc/dashyard/dashboards:ro
    command: ["serve", "--config", "/etc/dashyard/config.yaml", "--dashboards-dir", "/etc/dashyard/dashboards"]
    depends_on:
      - dummyprom

  dummyprom:
    build:
      context: ../..
      dockerfile: Dockerfile.dummyprom
